### PR TITLE
Fix #7

### LINKED ISSUE #7: it doesn't copy the empty line and space
Hi, there is a problem that the copy will only copy the characters but not include empty lines and space.  I am trying to find the reason.

### PR DESCRIPTION
**Pull request by madneal**

### CODE REVIEW

**Comment by sindresorhus** [comment]
Can you explain the fix?

**Comment by madneal** [comment]
@sindresorhus 
compare

**Comment by madneal** [comment]
@sindresorhus  I write a chrome extension, it seems that `style.all = unset` is the reason. I try to reproduce it in a html, but it does not work. But it really performs differently in this extension.
Moreover, I don't understand the significance to set `style.all = unset` here. And I have read the source code of [clipboard.js](https://github.com/zenorocha/clipboard.js), I don't find this. Could you explain this?

**Comment by sindresorhus** [comment]
> Moreover, I don't understand the significance to set style.all = unset here. And I have read the source code of clipboard.js, I don't find this. Could you explain this?

I just added it as an extra insurance that other styles wouldn't affect the element we create, but it should be totally fine without.

**Pull request merged**
