### PR TITLE
Export types

### PR DESCRIPTION
**Pull request by privatenumber**

### CODE REVIEW

**Comment by sindresorhus** [comment]
This is a breaking change for TS users, so I prefer to do it myself in the next major release. The types are already implicitly exported as it's named `index.d.ts`, which TS should check.

**Comment by privatenumber** [comment]
How is it a breaking change?

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/got/issues/2267

**Comment by privatenumber** [comment]
That's a breaking changes because the `types` property was removed from `package.json`. In this case, it's not because `index.d.ts` is at the root of the package where it can be detected.

In Node10 resolution mode, tsc checks the `types` property, and then falls back to checking `index.d.ts` at the root of the package. Therefore, that issue can be fixed by adding the top-level `types` property back. Node10 will look at `types` & Node16 will look at `exports.types`.

Here's the resolution trace using `moduleResolution: "node"` (via `tsc --traceResolution`):
```
======== Resolving module 'copy-text-to-clipboard' from '/index.ts'. ========
Explicitly specified module resolution kind: 'Node10'.
Loading module 'copy-text-to-clipboard' from 'node_modules' folder, target file types: TypeScript, Declaration.
Found 'package.json' at '/node_modules/copy-text-to-clipboard/package.json'.
File '/node_modules/copy-text-to-clipboard.ts' does not exist.
File '/node_modules/copy-text-to-clipboard.tsx' does not exist.
File '/node_modules/copy-text-to-clipboard.d.ts' does not exist.
'package.json' does not have a 'typesVersions' field.
'package.json' does not have a 'typings' field.
'package.json' does not have a 'types' field.
'package.json' does not have a 'main' field.
File '/node_modules/copy-text-to-clipboard/index.ts' does not exist.
File '/node_modules/copy-text-to-clipboard/index.tsx' does not exist.
File '/node_modules/copy-text-to-clipboard/index.d.ts' exists - use it as a name resolution result.
Resolving real path for '/node_modules/copy-text-to-clipboard/index.d.ts', result '/node_modules/copy-text-to-clipboard/index.d.ts'.
======== Module name 'copy-text-to-clipboard' was successfully resolved to '/node_modules/copy-text-to-clipboard/index.d.ts' with Package ID 'copy-text-to-clipboard/index.d.ts@3.1.0'. ========
```

Reproduction: https://stackblitz.com/edit/stackblitz-starters-hhbdf4?file=index.ts

**Pull request merged**
