### PR TITLE
docs(readme): add quote to example

### PR DESCRIPTION
**Pull request by AndersDJohnson**

### CODE REVIEW

**Comment by sindresorhus** [comment]
It already is correctly quoted.

**Comment by AndersDJohnson** [comment]
Weird, doesn't render correctly on my laptop. On my phone it looks correct already.

**Comment by AndersDJohnson** [comment]
Wow, I see it now. Barely.

screen shot 2017-07-18

**Comment by sindresorhus** [comment]
It looks good on my system (macOS):

screen shot 2017-07-18 at 17 23 31

**Pull request closed without merging**
