### PR TITLE
Restore previous selection after copying

### LINKED ISSUE #10: Reset selection to previous selection after copy
From: https://github.com/sindresorhus/refined-github/pull/487#discussion_r121921344

// @jgierer12

### PR DESCRIPTION
**Pull request by jgierer12**
Closes #10.

|Before|After
|-|-
|Before|After

### CODE REVIEW

**Comment by sindresorhus** [comment]
Doesn't seem to work when there's no selection:

```
index.html:30 Uncaught DOMException: Failed to execute 'getRangeAt' on 'Selection': 0 is not a valid index.
    at copyTextToClipboard (file:///Users/sindresorhus/dev/oss/copy-text-to-clipboard/index.html:30:37)
```

**Comment by jgierer12** [comment]
👍 fixed

**Comment by sindresorhus** [comment]
Would be better to check the `.rangeCount` instead of try/catch: https://stackoverflow.com/questions/22935320/uncaught-indexsizeerror-failed-to-execute-getrangeat-on-selection-0-is-not

**Comment by sindresorhus** [comment]
Great :)

**Comment by sindresorhus** [comment]
v1.0.2 published

**Pull request merged**
