### PR TITLE
Check support

### PR DESCRIPTION
**Pull request by ximet**
check support document.execCommand before work with code

### CODE REVIEW

**Comment by sindresorhus** [comment]
This module is for modern browsers, so support is assumed, but the try/catch is there just in case.

**Comment by ximet** [comment]
I agree with you. But Android Browser now modern, because in the World some people have Android 6 version. If using this code after call document.execCommand we have "undefined is not a function"

**Comment by sindresorhus** [comment]
Android 6 is not modern.

> If using this code after call document.execCommand we have "undefined is not a function"

I don't see how that's possible, since it's inside a try/catch: https://github.com/sindresorhus/copy-text-to-clipboard/blob/e616f95ff9b4d1b18f91a0dc10b22a512d4895a1/index.js#L20-L22 That error is probably because of something else.

**Comment by ximet** [comment]
Yes, you have try\catch, but you also createElement, and if document.execCommand not working in the browser, your element loses meaning. Better at first check working in browser execCommand and after working with this.

Android 6 is not modern, but still usable in 70% devices

**Comment by sindresorhus** [comment]
It will still work fine. It's just doing some slight unnecessary work if it's not supported, but it should have no impact.

> Android 6 is not modern, but still usable in 70% devices

Readme says "modern", not "popular". I'm not trying to be difficult, I just don't want to spend time on changing something that already works fine.

**Comment by ximet** [comment]
OMG, work if it's not supported it's very popular now. But if you think, you will understand that you are working with resource-intensive code.

> Readme says "modern", not "popular". I'm not trying to be difficult, I just don't want to spend time on changing something that already works fine.

In 2 sentences you says about "unnecessary work" and "work fine". It's very funny. I did not add complexity in your code, I just add one IF, which will provide nothing to do if there is no support

**Pull request closed without merging**
